# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0004_auto_20160722_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptortype',
            name='mandatory_for',
        ),
        migrations.AlterField(
            model_name='descriptortype',
            name='format',
            field=models.TextField(default='{"type": "string", "unit": "custom", "precision": "0.0", "fields": []}'),
        ),
    ]
