# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 14:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accession', '0005_auto_20160808_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptorgroup',
            name='content_type',
            field=models.ForeignKey(default=21, editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptorgroup',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 8, 14, 50, 26, 205493, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptorgroup',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1),
        ),
        migrations.AddField(
            model_name='descriptorgroup',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 8, 14, 50, 32, 455252, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptorgroup',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='descriptortype',
            name='content_type',
            field=models.ForeignKey(default=22, editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptortype',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 8, 14, 50, 43, 261447, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptortype',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1),
        ),
        migrations.AddField(
            model_name='descriptortype',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 8, 14, 50, 47, 509351, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptortype',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='descriptorvalue',
            name='content_type',
            field=models.ForeignKey(default=23, editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptorvalue',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 8, 14, 50, 56, 149408, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptorvalue',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1),
        ),
        migrations.AddField(
            model_name='descriptorvalue',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 8, 14, 51, 5, 117744, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptorvalue',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptorvalue',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='descriptorgroup',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='descriptortype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
