# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 'Create'), (1, 'Update'), (2, 'Delete'), (3, 'Remove'), (4, 'Action'), (5, 'M2M change')], default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fields', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.AlterIndexTogether(
            name='audit',
            index_together=set([('timestamp', 'id', 'user'), ('timestamp', 'id', 'user', 'content_type', 'object_id'), ('timestamp', 'id', 'content_type', 'object_id')]),
        ),
    ]
