# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='fields',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='type',
            field=models.IntegerField(choices=[(0, 'Create'), (1, 'Update'), (2, 'Delete'), (3, 'Remove'), (4, 'Action'), (5, 'M2M change')], default=0),
        ),
    ]
