# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20160624_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='reason',
        ),
        migrations.AlterIndexTogether(
            name='audit',
            index_together=set([('timestamp', 'id', 'content_type', 'object_id'), ('timestamp', 'id', 'user', 'content_type', 'object_id'), ('timestamp', 'id', 'user')]),
        ),
    ]
