# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 13:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='parent_list',
            field=models.CharField(blank=True, default='', max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='rank',
            field=models.IntegerField(choices=[(60, 'Family'), (61, 'Sub-family'), (70, 'Genus'), (71, 'Sub-genus'), (72, 'Section'), (73, 'Sub-section'), (80, 'Specie'), (81, 'Sub-specie'), (82, 'Variety')]),
        ),
        migrations.AlterField(
            model_name='taxonsynonym',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('la', 'Latin')], max_length=2),
        ),
        migrations.AlterField(
            model_name='taxonsynonym',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
