# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20161115_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='taxonsynonym',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='taxonsynonym',
            name='language',
            field=models.CharField(choices=[('la', 'Latin'), ('en', 'English'), ('fr', 'French')], max_length=2),
        ),
    ]
