# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20160415_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 24, 12, 49, 21, 847755, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxon',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1),
        ),
        migrations.AddField(
            model_name='taxon',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 24, 12, 49, 25, 31720, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxon',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='taxonsynonym',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 24, 12, 49, 28, 15839, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxonsynonym',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1),
        ),
        migrations.AddField(
            model_name='taxonsynonym',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 24, 12, 49, 30, 887827, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxonsynonym',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
