# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_taxonsynonym_synonym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonsynonym',
            name='synonym',
        ),
        migrations.AlterField(
            model_name='taxon',
            name='rank',
            field=models.IntegerField(choices=[(60, 'Family'), (61, 'Subfamily'), (65, 'Tribe'), (66, 'Subtribe'), (70, 'Genus'), (71, 'Subgenus'), (72, 'Section'), (73, 'Subsection'), (80, 'Specie'), (81, 'Subspecie'), (82, 'Variety'), (83, 'Subvariety'), (90, 'Cultivar')]),
        ),
        migrations.AlterField(
            model_name='taxonsynonym',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
