# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taxonomy', '0003_auto_20160624_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='content_type',
            field=models.ForeignKey(default=15, editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxonsynonym',
            name='content_type',
            field=models.ForeignKey(default=14, editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxon',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
