# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 15:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0004_auto_20161219_1651'),
        ('taxonomy', '0003_auto_20161219_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='descriptor_meta_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='descriptor.DescriptorMetaModel'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='descriptors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxonomy.Taxon'),
        ),
    ]
