# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_auto_20160707_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxon',
            options={'verbose_name': 'taxon'},
        ),
        migrations.AlterModelOptions(
            name='taxonsynonym',
            options={'verbose_name': 'taxon synonym'},
        ),
    ]
