# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 16:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_auto_20160718_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contains only alphanumerics characters or _ or - and be at least 3 characters length', regex=re.compile('^[a-zA-Z0-9_-]{3,}$', 34))]),
        ),
        migrations.AlterField(
            model_name='taxonsynonym',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contains only alphanumerics characters or _ or - and be at least 3 characters length', regex=re.compile('^[a-zA-Z0-9_-]{3,}$', 34))]),
        ),
    ]
