# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptortype',
            name='values',
            field=models.TextField(default=''),
        ),
    ]
