# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('descriptor', '0001_initial'),
        ('accession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='descriptor_meta_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptor.DescriptorMetaModel'),
        ),
        migrations.AddField(
            model_name='batchpanel',
            name='batches',
            field=models.ManyToManyField(to='accession.Batch'),
        ),
        migrations.AddField(
            model_name='batchpanel',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='batchaction',
            name='accession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accession.Accession'),
        ),
        migrations.AddField(
            model_name='batchaction',
            name='input_batches',
            field=models.ManyToManyField(related_name='_batchaction_input_batches_+', to='accession.Batch'),
        ),
        migrations.AddField(
            model_name='batchaction',
            name='output_batches',
            field=models.ManyToManyField(related_name='_batchaction_output_batches_+', to='accession.Batch'),
        ),
        migrations.AddField(
            model_name='batchaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='accession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='accession.Accession'),
        ),
        migrations.AddField(
            model_name='batch',
            name='batches',
            field=models.ManyToManyField(related_name='children', to='accession.Batch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='batch',
            name='descriptor_meta_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptor.DescriptorMetaModel'),
        ),
        migrations.AddField(
            model_name='accessionsynonym',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='accessionsynonym',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='accession.Accession'),
        ),
    ]
