# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('descriptor', '0001_initial'),
        ('accession', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='descriptor_meta_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='descriptor.DescriptorMetaModel'),
        ),
        migrations.AddField(
            model_name='batch',
            name='accession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='accession.Accession'),
        ),
        migrations.AddField(
            model_name='batch',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='batch',
            name='descriptor_meta_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='descriptor.DescriptorMetaModel'),
        ),
        migrations.AddField(
            model_name='asset',
            name='accessions',
            field=models.ManyToManyField(related_name='assets', to='accession.Accession'),
        ),
        migrations.AddField(
            model_name='asset',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='accessionsynonym',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='accession',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='accession',
            name='descriptor_meta_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessions', to='descriptor.DescriptorMetaModel'),
        ),
        migrations.AddField(
            model_name='accession',
            name='synonyms',
            field=models.ManyToManyField(related_name='accessions', to='accession.AccessionSynonym'),
        ),
    ]
