# Generated by Django 2.0.2 on 2018-02-08 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accession', '0001_initial'),
        ('descriptor', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchpanel',
            name='layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='descriptor.Layout'),
        ),
        migrations.AddField(
            model_name='batch',
            name='accession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='accession.Accession'),
        ),
        migrations.AddField(
            model_name='batch',
            name='batches',
            field=models.ManyToManyField(related_name='children', to='accession.Batch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='batch',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='descriptor.Layout'),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='action',
            name='accession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accession.Accession'),
        ),
        migrations.AddField(
            model_name='action',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='action',
            name='input_batches',
            field=models.ManyToManyField(related_name='_action_input_batches_+', to='accession.Batch'),
        ),
        migrations.AddField(
            model_name='action',
            name='output_batches',
            field=models.ManyToManyField(related_name='_action_output_batches_+', to='accession.Batch'),
        ),
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accession.ActionType'),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessionsynonym',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='accessionsynonym',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='accession.Accession'),
        ),
    ]
