# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
        ('main', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('descriptor', '0001_initial'),
        ('accession', '0002_auto_20170920_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessionsynonym',
            name='synonym_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EntitySynonymType'),
        ),
        migrations.AddField(
            model_name='accessionpanel',
            name='accessions',
            field=models.ManyToManyField(to='accession.Accession'),
        ),
        migrations.AddField(
            model_name='accessionpanel',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='accessionclassificationentry',
            name='accession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accession.Accession'),
        ),
        migrations.AddField(
            model_name='accessionclassificationentry',
            name='classification_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.ClassificationEntry'),
        ),
        migrations.AddField(
            model_name='accession',
            name='classifications_entries',
            field=models.ManyToManyField(related_name='accession_set', through='accession.AccessionClassificationEntry', to='classification.ClassificationEntry'),
        ),
        migrations.AddField(
            model_name='accession',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='accession',
            name='descriptor_meta_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptor.DescriptorMetaModel'),
        ),
        migrations.AddField(
            model_name='accession',
            name='primary_classification_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_accessions', to='classification.ClassificationEntry'),
        ),
        migrations.AlterIndexTogether(
            name='batchaction',
            index_together=set([('accession', 'type')]),
        ),
        migrations.AlterIndexTogether(
            name='accessionclassificationentry',
            index_together=set([('accession', 'primary'), ('accession', 'classification_entry')]),
        ),
    ]
