# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0002_auto_20170831_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchaction',
            options={'default_permissions': [], 'verbose_name': 'batch action'},
        ),
    ]
