# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('accession', '0002_auto_20170111_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Taxon'),
        ),
        migrations.AddField(
            model_name='accession',
            name='synonyms',
            field=models.ManyToManyField(related_name='accessions', to='accession.AccessionSynonym'),
        ),
    ]
