# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accession', '0002_auto_20161115_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='content_type',
            field=models.ForeignKey(default=26, editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1),
        ),
        migrations.AddField(
            model_name='sample',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='descriptor_meta_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptor.DescriptorMetaModel'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='descriptor_meta_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptor.DescriptorMetaModel'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='descriptor_meta_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptor.DescriptorMetaModel'),
        ),
    ]
