# Generated by Django 2.0.2 on 2018-02-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accession', '0002_auto_20180208_0950'),
        ('descriptor', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('classification', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessionsynonym',
            name='synonym_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.EntitySynonymType'),
        ),
        migrations.AddField(
            model_name='accessionpanel',
            name='accessions',
            field=models.ManyToManyField(to='accession.Accession'),
        ),
        migrations.AddField(
            model_name='accessionpanel',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='accessionpanel',
            name='layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='descriptor.Layout'),
        ),
        migrations.AddField(
            model_name='accessionclassificationentry',
            name='accession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accession.Accession'),
        ),
        migrations.AddField(
            model_name='accessionclassificationentry',
            name='classification_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.ClassificationEntry'),
        ),
        migrations.AddField(
            model_name='accession',
            name='classifications_entries',
            field=models.ManyToManyField(related_name='accession_set', through='accession.AccessionClassificationEntry', to='classification.ClassificationEntry'),
        ),
        migrations.AddField(
            model_name='accession',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='accession',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptor.Layout'),
        ),
        migrations.AddField(
            model_name='accession',
            name='primary_classification_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_accessions', to='classification.ClassificationEntry'),
        ),
        migrations.AlterIndexTogether(
            name='action',
            index_together={('accession', 'type')},
        ),
        migrations.AlterIndexTogether(
            name='accessionclassificationentry',
            index_together={('accession', 'primary'), ('accession', 'classification_entry')},
        ),
    ]
