# Generated by Django 2.0.2 on 2018-02-14 14:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accession', '0003_auto_20180208_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionToEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='action',
            old_name='type',
            new_name='action_type',
        ),
        migrations.AddField(
            model_name='action',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='action',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'steps': []}),
        ),
        migrations.AlterIndexTogether(
            name='action',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='actiontoentity',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accession.Action'),
        ),
        migrations.AddField(
            model_name='actiontoentity',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType'),
        ),
        migrations.RemoveField(
            model_name='action',
            name='accession',
        ),
        migrations.RemoveField(
            model_name='action',
            name='input_batches',
        ),
        migrations.RemoveField(
            model_name='action',
            name='output_batches',
        ),
        migrations.AlterIndexTogether(
            name='actiontoentity',
            index_together={('entity_type', 'entity_id')},
        ),
    ]
