# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0003_auto_20161014_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptormetamodel',
            name='descriptor_models',
        ),
        migrations.AddField(
            model_name='descriptormetamodel',
            name='descriptor_model_panels',
            field=models.ManyToManyField(related_name='descriptor_meta_models', through='accession.DescriptorPanel', to='accession.DescriptorModel'),
        ),
        migrations.AlterField(
            model_name='descriptormodeltype',
            name='descriptor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptor_model_types', to='accession.DescriptorType'),
        ),
    ]
