# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_auto_20161219_1651'),
        ('accession', '0003_auto_20161116_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Taxon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accession',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='accessionsynonym',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='accessionsynonym',
            name='language',
            field=models.CharField(choices=[('la', 'Latin'), ('en', 'English'), ('fr', 'French')], default='en', max_length=8),
        ),
        migrations.AlterField(
            model_name='asset',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='batch',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='sample',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
    ]
