# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 10:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0004_auto_20171114_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('label', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('format', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'verbose_name': 'batch action type',
            },
        ),
        migrations.AlterField(
            model_name='batchaction',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accession.BatchActionType'),
        ),
    ]
