# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0004_auto_20170216_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessionsynonym',
            name='accession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='accession.Accession'),
        ),
    ]
