# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 13:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0004_auto_20161219_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='descriptors',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='descriptors',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='descriptors',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
