# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0004_auto_20161026_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptormetamodel',
            old_name='descriptor_models_panels',
            new_name='descriptor_models',
        ),
    ]
