# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0004_accessionpanel_batchpanel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='accessions',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='content_type',
        ),
        migrations.AddField(
            model_name='accessionpanel',
            name='name',
            field=models.CharField(db_index=True, default='test', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchpanel',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
