# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0005_auto_20170220_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batches',
            field=models.ManyToManyField(related_name='children', to='accession.Batch'),
        ),
    ]
