# Generated by Django 2.0.2 on 2018-02-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0005_action_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
