# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 16:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0005_auto_20171130_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='descriptor_meta_model',
        ),
        migrations.AlterField(
            model_name='batchactiontype',
            name='format',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'type': 'undefined'}),
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
