# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0005_auto_20170911_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessionpanel',
            options={'permissions': (('get_accessionpanel', 'Can get a accession panel'), ('list_accessionpanel', 'Can list accession panel')), 'verbose_name': 'accession panel'},
        ),
        migrations.AlterModelOptions(
            name='batchpanel',
            options={'permissions': (('get_batchpanel', 'Can get a batch panel'), ('list_batchpanel', 'Can list batch panel')), 'verbose_name': 'batch panel'},
        ),
    ]
