# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 15:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0005_auto_20161221_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='descriptors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='batch',
            name='descriptors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='sample',
            name='descriptors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
