# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0006_auto_20171211_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchactiontype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
