# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accession', '0006_batch_batches'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(0, 'Introduction'), (1, 'Multiplication'), (2, 'Regeneration'), (3, 'Test'), (4, 'Clean-up'), (5, 'Sample'), (6, 'Dispatch'), (7, 'Elimination')], db_index=True, default=0)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accession.Accession')),
                ('input_batches', models.ManyToManyField(related_name='_batchaction_input_batches_+', to='accession.Batch')),
                ('output_batches', models.ManyToManyField(related_name='_batchaction_output_batches_+', to='accession.Batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.AlterIndexTogether(
            name='batchaction',
            index_together=set([('accession', 'type')]),
        ),
    ]
