# Generated by Django 2.0.2 on 2018-03-28 15:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0006_action_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('label', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accession.StockLocation')),
            ],
            options={
                'permissions': (('get_stocklocation', 'Can get a stock location'), ('list_stocklocation', 'Can list stock locations')),
                'verbose_name': 'stock location',
            },
        ),
        migrations.AlterModelOptions(
            name='accessionpanel',
            options={'permissions': (('get_accessionpanel', 'Can get a accession panel'), ('list_accessionpanel', 'Can list accession panels')), 'verbose_name': 'accession panel'},
        ),
        migrations.AlterField(
            model_name='accessionpanel',
            name='accessions',
            field=models.ManyToManyField(related_name='panels', to='accession.Accession'),
        ),
        migrations.AlterField(
            model_name='batchpanel',
            name='batches',
            field=models.ManyToManyField(related_name='panels', to='accession.Batch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='accession.StockLocation'),
        ),
    ]
