# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 08:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0001_initial'),
        ('accession', '0006_auto_20170912_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessionpanel',
            name='descriptor_meta_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='descriptor.DescriptorMetaModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessionpanel',
            name='descriptors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='batchpanel',
            name='descriptor_meta_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='descriptor.DescriptorMetaModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchpanel',
            name='descriptors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
