# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0007_auto_20170913_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessionpanel',
            name='descriptors',
        ),
        migrations.RemoveField(
            model_name='batchpanel',
            name='descriptors',
        ),
        migrations.AlterField(
            model_name='accessionpanel',
            name='descriptor_meta_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='descriptor.DescriptorMetaModel'),
        ),
        migrations.AlterField(
            model_name='batchpanel',
            name='descriptor_meta_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='descriptor.DescriptorMetaModel'),
        ),
    ]
