# Generated by Django 2.0.3 on 2018-04-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0007_auto_20180328_1749'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockLocation',
            new_name='StorageLocation',
        ),
        migrations.AlterModelOptions(
            name='storagelocation',
            options={'permissions': (('get_storagelocation', 'Can get a storage location'), ('list_storagelocation', 'Can list storage locations')), 'verbose_name': 'storage location'},
        ),
    ]
