# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0007_auto_20160808_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptorgroup',
            options={'verbose_name': 'descriptor group'},
        ),
        migrations.AlterModelOptions(
            name='descriptortype',
            options={'verbose_name': 'descriptor type'},
        ),
        migrations.AlterModelOptions(
            name='descriptorvalue',
            options={'verbose_name': 'descriptor value'},
        ),
        migrations.RemoveField(
            model_name='accessionsynonym',
            name='accession',
        ),
        migrations.AddField(
            model_name='accession',
            name='synonyms',
            field=models.ManyToManyField(related_name='accessions', to='accession.AccessionSynonym'),
        ),
        migrations.AddField(
            model_name='descriptorvalue',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=8),
        ),
        migrations.AlterField(
            model_name='accessionsynonym',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='descriptorvalue',
            unique_together=set([('language', 'descriptor')]),
        ),
    ]
