# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models

import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0007_auto_20170223_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessionsynonym',
            name='synonym',
        ),
        migrations.AddField(
            model_name='accession',
            name='code',
            field=models.CharField(db_index=True, default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accession',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='accessionsynonym',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='accessionsynonym',
            name='type',
            field=models.CharField(default='AC_001:0000003', max_length=64),
        ),
    ]
