# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0008_auto_20171218_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='descriptor_meta_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='descriptor.DescriptorMetaModel'),
        ),
        migrations.AlterField(
            model_name='accessionclassificationentry',
            name='accession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accession.Accession'),
        ),
        migrations.AlterField(
            model_name='accessionclassificationentry',
            name='classification_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.ClassificationEntry'),
        ),
        migrations.AlterField(
            model_name='accessionpanel',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='accessionpanel',
            name='descriptor_meta_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='descriptor.DescriptorMetaModel'),
        ),
        migrations.AlterField(
            model_name='accessionsynonym',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='accessionsynonym',
            name='synonym_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.EntitySynonymType'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='accession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='accession.Accession'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='descriptor_meta_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='descriptor.DescriptorMetaModel'),
        ),
        migrations.AlterField(
            model_name='batchaction',
            name='accession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accession.Accession'),
        ),
        migrations.AlterField(
            model_name='batchaction',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='batchaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batchactiontype',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='batchpanel',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='batchpanel',
            name='descriptor_meta_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='descriptor.DescriptorMetaModel'),
        ),
    ]
