# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accession', '0008_auto_20160908_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('verbose_name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'descriptor model',
            },
        ),
        migrations.CreateModel(
            name='DescriptorModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(default={})),
                ('mandatory', models.BooleanField(default=False)),
                ('set_once', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('descriptor_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptors_types', to='accession.DescriptorModel')),
            ],
            options={
                'verbose_name': 'descriptor model type',
            },
        ),
        migrations.CreateModel(
            name='DescriptorPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.TextField(default={})),
                ('position', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'descriptor panel',
            },
        ),
        migrations.AddField(
            model_name='descriptorvalue',
            name='ordinal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='descriptorvalue',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='accession.DescriptorValue'),
        ),
        migrations.AddField(
            model_name='descriptorvalue',
            name='value0',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AddField(
            model_name='descriptorvalue',
            name='value1',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='accessionsynonym',
            name='type',
            field=models.CharField(default='ID_001:0000001', max_length=16),
        ),
        migrations.AlterField(
            model_name='descriptortype',
            name='format',
            field=models.TextField(default='{"type": "string", "unit": "custom", "precision": "0.0", "fields": [], "trans": false}'),
        ),
        migrations.RemoveField(
            model_name='descriptorvalue',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='descriptorvalue',
            name='value',
        ),
        migrations.AlterUniqueTogether(
            name='descriptorvalue',
            unique_together=set([('descriptor', 'language')]),
        ),
        migrations.AlterIndexTogether(
            name='descriptorvalue',
            index_together=set([('descriptor', 'language', 'ordinal'), ('descriptor', 'language', 'value0'), ('descriptor', 'language', 'value1')]),
        ),
        migrations.AddField(
            model_name='descriptormodeltype',
            name='descriptor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accession.DescriptorType'),
        ),
        migrations.AddField(
            model_name='descriptormodeltype',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accession.DescriptorPanel'),
        ),
        migrations.AddField(
            model_name='accession',
            name='descriptor_model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='accessions', to='accession.DescriptorModel'),
            preserve_default=False,
        ),
    ]
