# Generated by Django 2.0.4 on 2018-04-09 11:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0008_auto_20180404_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField(default=0)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accession.Action')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='actiondata',
            unique_together={('action', 'step_index')},
        ),
    ]
