# Generated by Django 2.0.4 on 2018-04-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0009_auto_20180409_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondata',
            name='data_type',
            field=models.IntegerField(choices=[(0, 'Input'), (1, 'Output')], default=0),
        ),
    ]
