# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0009_auto_20160922_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptormodel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
