# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0009_auto_20170710_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessionsynonym',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
