# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 17:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0009_auto_20180105_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchaction',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'status': 'created'}),
        ),
    ]
