# Generated by Django 2.0.4 on 2018-04-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0010_actiondata_data_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actiondata',
            unique_together={('action', 'step_index', 'data_type')},
        ),
    ]
