# Generated by Django 2.0.4 on 2018-04-17 09:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0011_auto_20180409_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessionpanel',
            name='panel_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='action',
            name='format',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'steps': []}),
        ),
        migrations.AddField(
            model_name='batchpanel',
            name='panel_type',
            field=models.IntegerField(default=0),
        ),
    ]
