# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0012_auto_20160930_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessionsynonym',
            name='type',
            field=models.CharField(default='IN_001:0000001', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='descriptorvalue',
            unique_together=set([('id', 'language'), ('code', 'language')]),
        ),
    ]
