# Generated by Django 2.0.4 on 2018-06-26 12:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0012_auto_20180417_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='batch',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
