# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0013_auto_20160930_1434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='descriptorvalue',
            unique_together=set([('code', 'language')]),
        ),
    ]
