# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0015_auto_20160930_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptorvalue',
            name='ordinal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='descriptorvalue',
            name='value0',
            field=models.CharField(default='', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='descriptorvalue',
            name='value1',
            field=models.CharField(default='', max_length=127, null=True),
        ),
    ]
