# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20170921_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationentry',
            name='related',
            field=models.ManyToManyField(related_name='relate_to_classificationsentries', to='classification.ClassificationEntry'),
        ),
    ]
