# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20170904_1434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classificationrank',
            unique_together=set([('classification', 'level')]),
        ),
    ]
