# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_classificationentry_related'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificationentry',
            options={'permissions': (('list_classificationentry', 'Can list classification entry'),), 'verbose_name': 'classification entry'},
        ),
    ]
