# Generated by Django 2.0.4 on 2018-07-04 10:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_classificationentry_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationentry',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
