# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_auto_20170315_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonsynonym',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
