# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 12:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0005_auto_20170710_1729'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('classification', '0004_auto_20170710_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('label', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'classification',
            },
        ),
        migrations.CreateModel(
            name='ClassificationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('parent_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('descriptors', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('descriptor_meta_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='descriptor.DescriptorMetaModel')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='classification.ClassificationEntry')),
            ],
            options={
                'verbose_name': 'classifiction entry',
            },
        ),
        migrations.CreateModel(
            name='ClassificationEntrySynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('language', models.CharField(default='en', max_length=5)),
                ('type', models.IntegerField(choices=[(0, 'Primary'), (1, 'Synonym'), (2, 'Code')])),
                ('classification_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='classification.ClassificationEntry')),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'classification entry synonym',
            },
        ),
        migrations.CreateModel(
            name='ClassificationRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('label', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('level', models.IntegerField()),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='classification.Classification')),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'classification rank',
            },
        ),
        migrations.AddField(
            model_name='classificationentry',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.ClassificationRank'),
        ),
    ]
