# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitysynonymtype',
            name='multiple_entry',
            field=models.BooleanField(default=False),
        ),
    ]
