# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_eventmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='settings',
            field=models.TextField(default='{}'),
        ),
    ]
