# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(max_length=1024),
        ),
    ]
