# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170223_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmessage',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
