# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_modify', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'descriptor group',
            },
        ),
        migrations.CreateModel(
            name='DescriptorMetaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.TextField(default='{}')),
                ('description', models.TextField(blank=True, default='')),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'descriptor meta model',
            },
        ),
        migrations.CreateModel(
            name='DescriptorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('verbose_name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'descriptor model',
            },
        ),
        migrations.CreateModel(
            name='DescriptorModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.TextField(default='{}')),
                ('mandatory', models.BooleanField(default=False)),
                ('set_once', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('descriptor_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptor_model_types', to='descriptor.DescriptorModel')),
            ],
            options={
                'verbose_name': 'descriptor model type',
            },
        ),
        migrations.CreateModel(
            name='DescriptorPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.TextField(default='{}')),
                ('position', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('descriptor_meta_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='descriptor.DescriptorMetaModel')),
                ('descriptor_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='descriptor.DescriptorModel')),
            ],
            options={
                'verbose_name': 'descriptor panel',
            },
        ),
        migrations.CreateModel(
            name='DescriptorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('values', models.TextField(default='')),
                ('format', models.TextField(default='{"type": "string", "unit": "custom", "precision": "0.0", "fields": [], "trans": false}')),
                ('can_delete', models.BooleanField(default=True)),
                ('can_modify', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_set', to='descriptor.DescriptorGroup')),
            ],
            options={
                'verbose_name': 'descriptor type',
            },
        ),
        migrations.CreateModel(
            name='DescriptorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('la', 'Latin')], default='en', max_length=8)),
                ('code', models.CharField(max_length=64)),
                ('parent', models.CharField(max_length=64, null=True)),
                ('ordinal', models.IntegerField(default=0, null=True)),
                ('value0', models.CharField(default='', max_length=127, null=True)),
                ('value1', models.CharField(default='', max_length=127, null=True)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_set', to='descriptor.DescriptorType')),
            ],
            options={
                'verbose_name': 'descriptor value',
            },
        ),
        migrations.AddField(
            model_name='descriptormodeltype',
            name='descriptor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptor_model_types', to='descriptor.DescriptorType'),
        ),
        migrations.AddField(
            model_name='descriptormetamodel',
            name='descriptor_models',
            field=models.ManyToManyField(related_name='descriptor_meta_models', through='descriptor.DescriptorPanel', to='descriptor.DescriptorModel'),
        ),
        migrations.AddField(
            model_name='descriptormetamodel',
            name='target',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='descriptor_meta_models', to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='descriptorvalue',
            unique_together=set([('code', 'language')]),
        ),
        migrations.AlterIndexTogether(
            name='descriptorvalue',
            index_together=set([('descriptor', 'language', 'value1'), ('code', 'language'), ('descriptor', 'language', 'value0'), ('descriptor', 'language'), ('descriptor', 'language', 'ordinal')]),
        ),
    ]
