# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptortype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
