# Generated by Django 2.0.2 on 2018-03-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('descriptor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptorIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'None'), (1, 'Unique-BTree'), (2, 'BTree'), (3, 'GIN'), (4, 'GIST')], default=0)),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptor.Descriptor')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'descriptor index',
            },
        ),
        migrations.AlterUniqueTogether(
            name='descriptorindex',
            unique_together={('descriptor', 'target')},
        ),
    ]
