# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('descriptor', '0002_auto_20161116_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptorModelTypeCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Hidden'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('condition', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Defined'), (2, 'Equal to'), (3, 'Different from')], default=0)),
                ('values', models.TextField(default='')),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('descriptor_model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='descriptor.DescriptorModelType')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions_as_target', to='descriptor.DescriptorModelType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
