# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0003_descriptormodeltypecondition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptormodeltypecondition',
            options={'verbose_name': 'descriptor model type condition'},
        ),
        migrations.AlterField(
            model_name='descriptorgroup',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='descriptormetamodel',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='descriptormodel',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='descriptormodeltype',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='descriptormodeltypecondition',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='descriptorpanel',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='descriptortype',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='descriptorvalue',
            name='entity_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='descriptorvalue',
            name='language',
            field=models.CharField(choices=[('la', 'Latin'), ('en', 'English'), ('fr', 'French')], default='en', max_length=8),
        ),
    ]
