# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0003_descriptormodeltype_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptormodeltype',
            name='index',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Unique-BTree'), (2, 'BTree'), (3, 'GIN'), (4, 'GIST')], default=0),
        ),
    ]
