# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 15:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0004_auto_20170531_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptormetamodel',
            name='label',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='descriptormodeltype',
            name='label',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='descriptorpanel',
            name='label',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='descriptorvalue',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
