# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 09:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0005_auto_20170710_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptormetamodel',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'type': 'undefined'}),
        ),
        migrations.AlterField(
            model_name='descriptormodeltypecondition',
            name='values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='descriptortype',
            name='format',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'type': 'undefined'}),
        ),
        migrations.AlterField(
            model_name='descriptortype',
            name='values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
