# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=100)),
                ('models', models.ManyToManyField(to='contenttypes.ContentType')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set([('app_label', 'codename')]),
        ),
        migrations.AlterIndexTogether(
            name='action',
            index_together=set([('app_label', 'codename')]),
        ),
    ]
