# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 10:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('owner_object_id', models.IntegerField()),
                ('version', models.PositiveIntegerField(default=0)),
                ('file_name', models.CharField(max_length=256)),
                ('mime_type', models.CharField(max_length=64)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('label', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('description', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('copyright', models.CharField(blank=True, default='', max_length=1024)),
                ('year', models.IntegerField(default=None, null=True)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('owner_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'media',
            },
        ),
    ]
