# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0002_auto_20170208_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='copyright',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='media',
            name='label',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='media',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
