# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 15:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0003_auto_20170317_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='label',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
