# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 12:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0004_auto_20170710_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
