# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('level', models.IntegerField(choices=[(60, 'Family'), (61, 'Sub-family'), (70, 'Genus'), (71, 'Sub-genus'), (80, 'Specie'), (81, 'Sub-specie')])),
                ('parent_list', models.CharField(blank=True, default='', max_length=1024)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Taxon')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2)),
                ('type', models.IntegerField(choices=[(0, 'Primary'), (1, 'Synonym'), (2, 'Code')])),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Taxon')),
            ],
        ),
    ]
