# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxon',
            old_name='level',
            new_name='rank',
        ),
        migrations.AlterField(
            model_name='taxonsynonym',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='taxonomy.Taxon'),
        ),
    ]
