# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatename',
            name='alternate_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
