# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonames', '0002_alternatename_is_preferred_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternatename',
            name='is_short_name',
            field=models.BooleanField(default=False),
        ),
    ]
