# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonames', '0003_auto_20170331_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='alt_names',
        ),
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.AlterField(
            model_name='alternatename',
            name='alternate_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alternatename',
            name='language',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='state',
            name='source',
            field=models.CharField(db_index=True, max_length=1024, unique=True),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
