# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grc',
            name='organisations',
            field=models.ManyToManyField(related_name='grcs', to='organisation.Organisation'),
        ),
    ]
