# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20171114_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='descriptor_meta_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='descriptor.DescriptorMetaModel'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='descriptor_meta_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='descriptor.DescriptorMetaModel'),
        ),
    ]
