# Generated by Django 2.0.4 on 2018-06-20 10:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('descriptor', '0002_auto_20180328_1749'),
        ('organisation', '0003_person_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conservatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Valid'), (2, 'Archived'), (3, 'Removed')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('descriptors', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Establishment')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptor.Layout')),
            ],
            options={
                'verbose_name': 'Conservatory',
            },
        ),
    ]
