# Generated by Django 2.0.4 on 2018-06-26 12:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_conservatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservatory',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='establishment',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='organisation',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='person',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
